agrobusiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.mail import send_mail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('fields/', include(('fields.urls', 'fields'), namespace='fields')),
    path('activities/', include(('activities.urls', 'activities'), namespace='activities')),
    path('partner/', include(('partner.urls', 'partner'), namespace='partner')),
    path('activitycontrol/', include(('activitycontrol.urls', 'activitycontrol'), namespace='activitycontrol')),
    path('supplies/', include(('supplies.urls', 'supplies'), namespace='supplies')),
    path('home/', include(('home.urls', 'home'), namespace='home')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="reset_password.html",
        email_template_name="custom_password_reset_email.html"
    ), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),

    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
         name="password_reset_complete"),

]
from django.conf.urls import handler500
from django.conf.urls import handler404

handler500 = 'home.views.custom_500'

handler404 = 'home.views.custom_404'

home/urls.py
from django.urls import path
from . import views
from users.views import login

urlpatterns = [
    path('import-geral/', views.import_geral, name='import-geral'),
    path('', views.home, name='home'),
    path('fields/get/', views.get_fields, name='get_fields'),
    path('activities/get/', views.get_activities, name='get_activities'),
    path('partner/get/', views.get_partner, name='get_partner'),
    path('activitycontrol/get/', views.get_activitycontrol, name='get_activitycontrol'),
    path('supplies/get/', views.get_supplies, name='get_supplies'),
    path('users/login/', login, name='login'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomPasswordChangeView


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user-settings/', views.user_settings, name='user_settings'),
    #path('alterar-senha/user-settings', views.alterar_senha, name='alterar_senha'),
    path('password_change/', CustomPasswordChangeView.as_view(template_name='password_change_form.html'),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as login_dj, logout as logout_dj
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView

def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    username = request.POST.get('username')
    password = request.POST.get('password')
    print(password)
    user = authenticate(username=username, password=password)
    if user:
        login_dj(request, user)
        return redirect("home")
    else:
        messages.success(request, ("Usuário ou senha inválidos."))
        return redirect('/users/login')


def logout(request):
    logout_dj(request)
    return redirect('/users/login')

@login_required
def user_settings(request):
    if request.method == "GET":
        return render(request, 'user_settings.html')
    user = request.user
    user.first_name = request.POST.get('firstName')
    user.last_name = request.POST.get('lastName')
    user.email = request.POST.get('email')
    user.save()
    return redirect('users:user_settings')

class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('users:password_change_done')

users/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />


  <title>Agro - Login</title>

  <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">
    <link href="{% static 'plugins/material/css/materialdesignicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'plugins/simplebar/simplebar.css' %}" rel="stylesheet" />

  <!-- PLUGINS CSS STYLE -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="{% static 'plugins/nprogress/nprogress.css' %}" rel="stylesheet" />
  
  <!-- MONO CSS -->
    <link id="main-css-href" rel="stylesheet" href="{% static 'css/style.css' %}" />

  <!-- FAVICON -->
  <link href="{% static 'images/favicon.png' %}" rel="shortcut icon" />
    <script src="{% static 'js/showpassword.js' %}"></script>
    <script src="{% static 'js/sweetalert.js' %}"></script>
    <script src="{% static 'plugins/nprogress/nprogress.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

</head>
  <body>
        <div class="container">

        </div>
        <div class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-md-10">
                <div class="card card-default mb-0">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                      <a class="w-auto pl-0" href="/index.html">
                        <!--<img src="images/logo.png" alt="Mono">-->
                        <span class="brand-name text-dark">CloupOne - Agro</span>
                      </a>
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">

                    <h4 class="text-dark mb-6 text-center">Entrar</h4>

                    <form action="{% url 'users:login' %}" method="POST">{% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                          <input type="text" class="form-control input-lg" id="username" name="username"
                            placeholder="usuário">
                        </div>
                       <div class="form-group col-md-12 relative">
                         <input type="password" class="form-control input-lg" id="password" name="password" placeholder="Senha">
                         <i class="bi bi-eye-fill toggle-password" id="btn-password" onclick="showPassword()"></i>
                       </div>
                        <div class="col-md-12 text-center">


                         <div class="d-flex justify-content-between mb-3">

                           <div class="custom-control custom-checkbox mr-3 mb-3">
                              <input type="checkbox" class="custom-control-input" id="customCheck2">
                              <label class="custom-control-label" for="customCheck2">Lembrar usuário</label>
                            </div>

                            <a class="text-color" href="{% url 'reset_password'%}"> Esqueceu a senha? </a>

                          </div>

                          <button type="submit" class="btn btn-primary btn-pill mb-4">Entrar</button>
                            {% if messages%}
                              {% for message in messages%}
                               <div class="alert alert-secondary" role="alert">
                                {{ message }}
                                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>

                              {% endfor %}
                            {% endif %}
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>



</body>
</html>

users/templates/password_change_done.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alteração de Senha Concluída</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link id="main-css-href" rel="stylesheet" href="{% static 'css/style.css' %}" />

    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 500px;
            padding: 40px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #007bff;
        }

        p {
            font-size: 18px;
            margin-bottom: 20px;
            line-height: 1.6;
            color: #555;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            transition: background-color 0.3s;
        }

        .btn:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Alteração de Senha Concluída</h1>
        <p>Sua senha foi alterada com sucesso!</p>
        <a href="{% url 'users:user_settings' %}" class="btn">Voltar para as Configurações</a>
    </div>
</body>
</html>
{% endblock content %}

users/templates/password_change_form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">

    <!-- PLUGINS CSS STYLE -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alterar Senha</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 400px;
            padding: 40px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
            position: relative;
        }

        h3 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #007bff;
        }

        .form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .form input[type="password"],
        .form input[type="text"],
        .form input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            position: relative;
        }

        .password-icon {
            position: absolute;
            top: 50%;
            right: 5px;
            transform: translateY(-50%);
            cursor: pointer;
        }

        .form input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .form input[type="submit"]:hover {
            background-color: #7da9eb;
        }

        p {
            font-size: 16px;
            margin-top: 20px;
        }
        ul{
            margin-top:15px;
        }
        .error-card {
            color: #ffdce9;
            background-color: #fd5190;
            border-color: #fd5190;
            position: relative;
            border: 1px solid transparent;
            border-radius: 0.25rem;
            margin-bottom: 15px;
            padding: 10px;
            display: none;
        }

        .close-button {
            position: absolute;
            top: 5px;
            right: 10px;
            cursor: pointer;
            color: #000;
            background-color: transparent;
            border: 0;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h3>Alterar Senha</h3>
        <form class="form" method="post" action="" onsubmit="return validateForm()">
            <div class="form-group">
                <label for="id_old_password">Senha Antiga:</label>
                <div style="position: relative;">
                    <input type="password" name="old_password" id="id_old_password">
                    <i class="bi bi-eye-fill password-icon" onclick="showPassword('id_old_password')"></i>
                </div>
            </div>
            <div class="form-group">
                <label for="id_new_password1">Nova Senha:</label>
                <div style="position: relative;">
                    <input type="password" name="new_password1" id="id_new_password1">
                    <i class="bi bi-eye-fill password-icon" onclick="showPassword('id_new_password1')"></i>
                </div>
            </div>
            <div class="form-group">
                <label for="id_new_password2">Confirme a Nova Senha:</label>
                <div style="position: relative;">
                    <input type="password" name="new_password2" id="id_new_password2">
                    <i class="bi bi-eye-fill password-icon" onclick="showPassword('id_new_password2')" style="margin-left: -25px;"></i>
                </div>
            </div>
            <input type="submit" value="Alterar Senha" class="btn btn-primary">
            {% csrf_token %}
        </form>
        <div class="error-card" id="error-card">
            <span class="close-button" onclick="closeErrorMessage()">&times;</span>
            <p id="error-message" class="error-message"></p>
        </div>
        <ul>
            <li>A sua senha não pode ser similar às suas informações pessoais.</li>
            <li>A sua senha deve conter pelo menos 8 caracteres.</li>
            <li>A sua senha não pode ser uma senha comum.</li>
            <li>A sua senha não pode ter apenas números.</li>
        </ul>
        <p>Deseja voltar? <a href="{% url 'home' %}">Home</a></p>
    </div>

    <script>
        function showPassword(inputId) {
            var inputPass = document.getElementById(inputId);
            var btnShowPass = inputPass.nextElementSibling;

            if (inputPass.type === 'password') {
                inputPass.setAttribute('type', 'text');
                btnShowPass.classList.remove('bi-eye-fill');
                btnShowPass.classList.add('bi-eye-slash-fill');
            } else {
                inputPass.setAttribute('type', 'password');
                btnShowPass.classList.remove('bi-eye-slash-fill');
                btnShowPass.classList.add('bi-eye-fill');
            }
        }

        function validateForm() {
            var oldPassword = document.getElementById('id_old_password').value;
            var new_password1 = document.getElementById('id_new_password1').value;
            var new_password2 = document.getElementById('id_new_password2').value;
            var errorMessage = document.getElementById('error-message');
            var errorCard = document.getElementById('error-card');

            if (new_password1 !== new_password2) {
                errorMessage.textContent = 'As senhas não são iguais.';
                errorCard.style.display = 'block';
                return false;
            }

            errorMessage.textContent = '';
            errorCard.style.display = 'none';
            return true;
        }

        function closeErrorMessage() {
            var errorCard = document.getElementById('error-card');
            errorCard.style.display = 'none';
        }
    </script>
</body>
</html>

users/templates/user_settings.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}Dados do usuário{% endblock %}
{% block 'page_title' %}Dados do usuário{% endblock %}

{% block 'body' %}

<script src="{% static 'js/sweetalert.js' %}"></script>
<script src="{% static 'js/scriptsform.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10/sweetalert2.all.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10/sweetalert2.min.css">
<style>/* Estilos para a modal */
.modal {
    display: none; /* Oculta a modal por padrão */
    position: fixed; /* Posiciona a modal de forma fixa na tela */
    z-index: 1000; /* Define a ordem de empilhamento */
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto; /* Adiciona rolagem se necessário */
    background-color: rgba(0, 0, 0, 0.4); /* Fundo semi-transparente */
}

.modal-content {
    background-color: #fefefe;
    margin: 10% auto; /* Centraliza a modal verticalmente e a posiciona a 10% da parte superior */
    padding: 20px;
    border: 1px solid #888;
    width: 60%; /* Largura da modal */
    max-width: 400px; /* Largura máxima da modal */
    border-radius: 8px; /* Borda arredondada */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra */
}

/* Estilos para o botão de fechar */
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
}
.btn#botaoAlterarSenha{
margin-left:10px;

}

</style>

<div class="card card-default">
    <div class="card-header">
        <h2 class="mb-5">Meu perfil</h2>
    </div>

    <div class="card-body">

        <form id="profileForm" action="{% url 'users:user_settings' %}" method="POST">
            {% csrf_token %}
            <div class="form-group mb-4">
                <label for="userName">User name</label>
                <input type="text" class="form-control" id="userName" value="{{ user.username }}" readonly>
            </div>

            <div class="row mb-2">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="firstName">First name</label>
                        <input type="text" class="form-control" id="firstName" name="firstName" value="{{ user.first_name }}" autocomplete="off">
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="lastName">Last name</label>
                        <input type="text" class="form-control" id="lastName" name="lastName" value="{{ user.last_name }}" autocomplete="off">
                    </div>
                </div>
            </div>

            <div class="form-group mb-4">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}">
            </div>

            <div class="d-flex justify-content-end mt-6">
                <button id="botaoEnviar" type="submit" class="btn btn-primary mb-2 btn-pill" autocomplete="off">Atualizar perfil</button>
                <button id="botaoAlterarSenha" type="button" class="btn btn-primary mb-2 btn-pill" autocomplete="off">Alterar senha</button>
            </div>
        </form>
    </div>
</div>

<!-- Modal de alteração de senha
<div id="modalAlterarSenha" class="modal" style="display: none;">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Alterar Senha</h2>
        <form id="formAlterarSenha" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="novaSenha">Nova Senha</label>
                <input type="password" class="form-control" id="novaSenha" name="novaSenha">
            </div>
            <button id="botaoAlterarSenha" type="submit" class="btn btn-primary mb-2 btn-pill" autocomplete="off">Alterar senha</button>
        </form>
    </div>
</div>-->

<script>
    document.getElementById('profileForm').addEventListener('submit', function(event) {
        event.preventDefault();

        Swal.fire({
            title: 'Confirmação',
            text: 'Deseja realmente atualizar o perfil?',
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: 'Sim',
            cancelButtonText: 'Não'
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire({
                    title: 'Sucesso!',
                    text: 'Perfil atualizado com sucesso.',
                    icon: 'success'
                }).then(() => {
                    this.submit(); // Envie o formulário
                });
            }
        });
    });

   document.addEventListener('DOMContentLoaded', function() {
    var modalAlterarSenha = document.getElementById('modalAlterarSenha');
    var btnAlterarSenha = document.getElementById('botaoAlterarSenha');
    var spanClose = document.getElementsByClassName('close')[0];

    btnAlterarSenha.onclick = function() {
        modalAlterarSenha.style.display = 'block';
    }

    spanClose.onclick = function() {
        modalAlterarSenha.style.display = 'none';
    }

    window.onclick = function(event) {
        if (event.target == modalAlterarSenha) {
            modalAlterarSenha.style.display = 'none';
        }
    }

    var formAlterarSenha = document.getElementById('formAlterarSenha');
    formAlterarSenha.addEventListener('submit', function(event) {
        event.preventDefault(); // Evita o comportamento padrão de envio do formulário

        var formData = new FormData(formAlterarSenha);

        fetch('{% url "users:user_settings" %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                swal.fire({
                    icon: 'success',
                    title: 'Sucesso!',
                    text: 'Sua senha foi alterada com sucesso!'
                });
                modalAlterarSenha.style.display = 'none';
            } else {
                // Se ocorreu algum erro, exiba uma mensagem de erro
                swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Algo deu errado!'
                });
            }
        })
        .catch(error => {
            console.error('Erro:', error);
        });
    });
});
    document.getElementById("botaoAlterarSenha").addEventListener("click", function() {
    window.location.href = "{% url 'users:password_change' %}";
});


</script>

{% endblock %}