agrobusiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.mail import send_mail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('fields/', include(('fields.urls', 'fields'), namespace='fields')),
    path('activities/', include(('activities.urls', 'activities'), namespace='activities')),
    path('partner/', include(('partner.urls', 'partner'), namespace='partner')),
    path('activitycontrol/', include(('activitycontrol.urls', 'activitycontrol'), namespace='activitycontrol')),
    path('supplies/', include(('supplies.urls', 'supplies'), namespace='supplies')),
    path('home/', include(('home.urls', 'home'), namespace='home')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="reset_password.html",
        email_template_name="custom_password_reset_email.html"
    ), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),

    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
         name="password_reset_complete"),

]
from django.conf.urls import handler500
from django.conf.urls import handler404

handler500 = 'home.views.custom_500'

handler404 = 'home.views.custom_404'

home/urls.py
from django.urls import path
from . import views
from users.views import login

urlpatterns = [
    path('import-geral/', views.import_geral, name='import-geral'),
    path('', views.home, name='home'),
    path('fields/get/', views.get_fields, name='get_fields'),
    path('activities/get/', views.get_activities, name='get_activities'),
    path('partner/get/', views.get_partner, name='get_partner'),
    path('activitycontrol/get/', views.get_activitycontrol, name='get_activitycontrol'),
    path('supplies/get/', views.get_supplies, name='get_supplies'),
    path('users/login/', login, name='login'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomPasswordChangeView


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user-settings/', views.user_settings, name='user_settings'),
    #path('alterar-senha/user-settings', views.alterar_senha, name='alterar_senha'),
    path('password_change/', CustomPasswordChangeView.as_view(template_name='password_change_form.html'),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt" dir="ltr">
  <head>
      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
      <link rel="icon" type="image/x-icon" href="projeto/logo.png">
      <title>{% block 'title' %}{% endblock %}</title>

  <!-- GOOGLE FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link href="{% static 'plugins/material/css/materialdesignicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'plugins/simplebar/simplebar.css' %}" rel="stylesheet" />

  <!-- PLUGINS CSS STYLE -->
  <link href="{% static 'plugins/nprogress/nprogress.css' %}" rel="stylesheet" />

  <link href="{% static 'plugins/prism/prism.css' %}" rel="stylesheet" />
  
  <!-- MONO CSS -->
  <link id="main-css-href" rel="stylesheet" href="{% static 'css/style.css' %}" />

  

  <!-- FAVICON -->
  <link href="{% static 'images/favicon.png' %}" rel="shortcut icon" />
  <script src="{% static 'plugins/nprogress/nprogress.js' %}"></script>
</head>


  <body class="navbar-fixed sidebar-fixed" id="body">
    <script>
      NProgress.configure({ showSpinner: false });
      NProgress.start();

    </script>
 
    <div class="wrapper">
      
      
        <!-- ====================================
          ——— LEFT SIDEBAR WITH OUT FOOTER
        ===================================== -->
        <aside class="left-sidebar sidebar-dark" id="left-sidebar">
          <div id="sidebar" class="sidebar sidebar-with-footer">
            <!-- Aplication Brand -->
            <div class="app-brand">
              <a href="{% url 'home' %}">
                <span class="brand-name">CloupOne - Agro</span>

              </a>
            </div>
            <!-- begin sidebar scrollbar -->
            <div class="sidebar-left" data-simplebar style="height: 100%;">
              <!-- sidebar menu -->
              <ul class="nav sidebar-inner" id="sidebar-menu">
                  </li>
                    <li class="section-title">
                    Atividades
                    </li>
                  <li>
                    <a class="sidenav-item-link" href="http://127.0.0.1:8000/activitycontrol/get-activitycontrol/">
                      <i class="bi bi-search"></i>
                      <span class="nav-text">Consultar atividades</span>
                    </a>
                  </li>
                  <li class="section-title">
                    Parceiros
                    </li>
                  <li>
                    <a class="sidenav-item-link" href="http://127.0.0.1:8000/partner/get-partner/">
                      <i class="bi bi-search"></i>
                      <span class="nav-text">Consulta de parceiros</span>
                    </a>
                  </li>
              </ul>
            </div>

            <div class="sidebar-footer">
              <div class="sidebar-footer-content">
                <ul class="d-flex">
                 <!-- <li>
                    <a href="user-account-settings.html" data-toggle="tooltip" title="Profile settings"><i class="mdi mdi-settings"></i></a></li>
                  <li>
                    <a href="#" data-toggle="tooltip" title="No chat messages"><i class="mdi mdi-chat-processing"></i></a>
                  </li>-->
                </ul>
              </div>
            </div>
          </div>
        </aside>

      

      <!-- ====================================
      ——— PAGE WRAPPER
      ===================================== -->
      <div class="page-wrapper">
        
          <!-- Header -->
          <header class="main-header" id="header">
            <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
              <!-- Sidebar toggle button -->
              <button id="sidebar-toggler" class="sidebar-toggle">
                <span class="sr-only">Toggle navigation</span>
              </button>

              <span class="page-title">{% block 'page_title' %}{% endblock %}</span>

              <div class="navbar-right ">
                <ul class="nav navbar-nav">
                  <!-- User Account -->
                  <li class="dropdown user-menu">
                    <button class="dropdown-toggle nav-link" data-toggle="dropdown">
                         <i class="bi bi-person"></i>
                        <span> <class="d-none d-lg-inline-block">{{ user.first_name }} {{ user.last_name }}</class> </span>

                    </button>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <li>
                        <a class="dropdown-link-item" href="{% url 'users:user_settings' %}">
                          <i class="mdi mdi-account-outline"></i>
                          <span class="nav-text">Meu perfil</span>
                        </a>
                      </li>
                      <li class="dropdown-footer">
                        <a class="dropdown-link-item" href="{% url 'users:logout' %}"> <i class="mdi mdi-logout"></i> Sair </a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>


          </header>

        <!-- ====================================
        ——— CONTENT WRAPPER
        ===================================== -->
        <div class="content-wrapper">
          <div class="content"><!-- For Components documentaion -->

      {% block 'body' %}{% endblock %}
      <!--  </div>
          <footer class="footer mt-auto">
            <div class="copyright bg-white">
              <p>
                &copy; <span id="copy-year"></span> Copyright <a class="text-primary" href="" target="_blank" >Giovani</a>.
              </p>
            </div>
            <script>
                var d = new Date();
                var year = d.getFullYear();
                document.getElementById("copy-year").innerHTML = year;
            </script>
          </footer>

      </div>-->


                    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
                    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
                    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
                    <script src="{% static 'plugins/simplebar/simplebar.min.js' %}"></script>
                    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>

                    <script src="{% static 'plugins/prism/prism.js' %}"></script>
                    <script src="{% static 'plugins/apexcharts/apexcharts.js' %}"></script>
                    
                    <script src="{% static 'js/mono.js' %}"></script>
                    <script src="{% static 'js/calendar.js' %}"></script>
                    <script src="{% static 'js/modalactivities.js' %}"></script>
                    <script src="{% static 'js/modalpartner.js' %}"></script>
                    <script src="{% static 'js/chart.js' %}"></script>
                    <script src="{% static 'js/map.js' %}"></script>
                    <script src="{% static 'js/custom.js' %}"></script>

  </body>
</html>

templates/custom_password_reset_email.html
Redefinição de Senha

Olá!

Você está recebendo este e-mail porque solicitou a redefinição de sua senha da plataforma AgroBusiness.

Acesse o link abaixo para redefinir sua senha.
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Se você não solicitou uma redefinição de senha, ignore este e-mail.
Seu usuário é: {{user}}

Obrigado!

templates/password_reset_complete.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Sent</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link id="main-css-href" rel="stylesheet" href="{% static 'css/style.css' %}" />

    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 500px;
            padding: 40px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h3 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #007bff;
        }

        p {
            font-size: 18px;
            margin-bottom: 20px;
            line-height: 1.6;
            color: #555;
        }
        .btn{
            margin:auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <h3>Senha redefinida com sucesso!</h3>
        <a href="{% url 'home' %}" class="btn btn-primary btn-pill mb-4">Voltar para tela de login</a>
    </div>
</body>
</html>
{% endblock content %}

templates/reset.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">

    <!-- PLUGINS CSS STYLE -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redefinir Senha</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 400px;
            padding: 40px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
            position: relative;
        }

        h3 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #007bff;
        }

        .form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .form input[type="password"],
        .form input[type="text"],
        .form input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            position: relative;
        }

        .password-icon {
            position: absolute;
            top: 50%;
            right: 5px;
            transform: translateY(-50%);
            cursor: pointer;
        }

        .form input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .form input[type="submit"]:hover {
            background-color: #7da9eb;
        }

        p {
            font-size: 16px;
            margin-top: 20px;
        }
        ul{
            margin-top:15px;
        }
        .error-card {
            color: #ffdce9;
            background-color: #fd5190;
            border-color: #fd5190;
            position: relative;
            border: 1px solid transparent;
            border-radius: 0.25rem;
        }

        .close-button {
            position: absolute;
            top: 53%;
            transform: translate(50%, -50%);
            cursor: pointer;
            box-sizing: content-box;
            width: 25px;
            margin-left: 80px;
            color: #000;
            border: 0;
            border-radius: 0.25rem;
            opacity: .5;
            font-size:25px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h3>Redefinir Senha</h3>
        <form class="form" method="post" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_new_password1">Nova Senha:</label>
                <div style="position: relative;">
                    <input type="password" name="new_password1" id="id_new_password1">
                    <i class="bi bi-eye-fill password-icon" onclick="showPassword('id_new_password1')"></i>
                </div>
            </div>
            <div class="form-group">
                <label for="id_new_password2">Confirme a Nova Senha:</label>
                <div style="position: relative;">
                    <input type="password" name="new_password2" id="id_new_password2">
                    <i class="bi bi-eye-fill password-icon" onclick="showPassword('id_new_password2')" style="margin-left: -25px;"></i>
                </div>
            </div>
            <input type="submit" value="Redefinir Senha" class="btn btn-primary">
        </form>
        <div class="error-card" id="error-card" style="display:none;">
            <span class="close-button" onclick="closeErrorMessage()">&times;</span>
            <p id="error-message" class="error-message"></p>
        </div>
        <ul>
            <li>A sua senha não pode ser similar às suas informações pessoais.</li>
            <li>A sua senha deve conter pelo menos 8 caracteres.</li>
            <li>A sua senha não pode ser uma senha comum.</li>
            <li>A sua senha não pode ter apenas números.</li>
        </ul>
        <p>Lembrou sua senha? <a href="{% url 'home' %}">Faça login</a></p>
    </div>

    <script>
        function showPassword(inputId) {
            var inputPass = document.getElementById(inputId);
            var btnShowPass = inputPass.nextElementSibling;

            if (inputPass.type === 'password') {
                inputPass.setAttribute('type', 'text');
                btnShowPass.classList.remove('bi-eye-fill');
                btnShowPass.classList.add('bi-eye-slash-fill');
            } else {
                inputPass.setAttribute('type', 'password');
                btnShowPass.classList.remove('bi-eye-slash-fill');
                btnShowPass.classList.add('bi-eye-fill');
            }
        }

        function validateForm() {
            var password1 = document.getElementById('id_new_password1').value;
            var password2 = document.getElementById('id_new_password2').value;
            var errorMessage = document.getElementById('error-message');
            var errorCard = document.getElementById('error-card');

            if (password1 !== password2) {
                errorMessage.textContent = 'As senhas não são iguais.';
                errorCard.style.display = 'block';
                return false;
            }

            errorMessage.textContent = '';
            errorCard.style.display = 'none';
            return true;
        }

        function closeErrorMessage() {
            var errorCard = document.getElementById('error-card');
            errorCard.style.display = 'none';
        }
    </script>
</body>
</html>

templates/reset_password.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redefinir Senha</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
         <link id="main-css-href" rel="stylesheet" href="{% static 'css/style.css' %}" />

    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 400px;
            padding: 40px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h3 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #007bff;
        }

        .form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .form input[type="text"],
        .form input[type="email"],
        .form input[type="password"],
        .form input[type="submit"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        .form input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.3s;
            border-radius:50px;
            width:150px;
        }

        .form input[type="submit"]:hover {
            background-color: #0056b3;
        }

        p {
            font-size: 16px;
            margin-top: 20px;
            color: #555;
        }
         .btn{
            margin:20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h3>Redefinir Senha</h3>
        <form class="form" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn" type="submit" value="Enviar">
        </form>
        <a href="{% url 'home' %}" class="btn btn-primary btn-pill mb-4">Voltar para tela de login</a>
    </div>
</body>
</html>
{% endblock content %}

templates/reset_password_sent.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Sent</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
     <link id="main-css-href" rel="stylesheet" href="{% static 'css/style.css' %}" />
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            max-width: 500px;
            padding: 40px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h3 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #007bff;
        }

        p {
            font-size: 18px;
            margin-bottom: 20px;
            line-height: 1.6;
            color: #555;
        }
        .btn{
            margin:auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <h3>E-mail para redefinição de senha enviado</h3>
        <p>Nós enviamos as instruções para redefinir sua senha por e-mail, caso exista uma conta associada ao endereço de e-mail que você inseriu. Você deverá recebê-las em breve.</p>
        <p>Se caso você não receber o e-mail, por favor, certifique-se de que inseriu o endereço com o qual se registrou e verifique sua pasta de spam.</p>
        <a href="{% url 'home' %}" class="btn btn-primary btn-pill mb-4">Voltar para tela de login</a>

    </div>
</body>
</html>
{% endblock content %}